=== srug86/restaurant-management-using-nfc.receiver/design/Rooms.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT Rooms (Room)+>
<!ELEMENT Room (Width, Height, Tables, Capacity)>
<!ATTLIST Room name(#PCDATA)>
<!ELEMENT Width (#PCDATA)>
<!ELEMENT Height (#PCDATA)>
<!ELEMENT Tables (#PCDATA)>
<!ELEMENT Capacity (#PCDATA)>

=== srug86/restaurant-management-using-nfc.receiver/design/Rooms.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Rooms SYSTEM "Rooms.dtd">
<Rooms>
	<Room name="Room1">
		<Width>12</Width>
		<Height>8</Height>
		<Tables>9</Tables>
		<Capacity>36</Capacity>
	</Room>
	<Room name="Room2">
		<Width>16</Width>
		<Height>12</Height>
		<Tables>12</Tables>
		<Capacity>48</Capacity>
	</Room>
</Rooms>
